export const enum EIcons {
  Dashboard = "unjs:theme-colors",
  User = "mdi:user",
  Home = "mdi-light:format-indent-increase",
  MenuOpen = "mdi-light:format-indent-decrease",
  MenuClose = "mdi-light:format-indent-increase",
  Fullscreen = "akar-icons:full-screen",
  Locale = "mdi:language",
  Theme = "unjs:theme-colors",
  Close = "akar-icons:x-small",
  Setting = "ep:setting",
  Edit = "cuida:edit-outline",
  Delete = "material-symbols:delete-outline",
  Plus = "ic:baseline-plus",
  Download = "material-symbols:download",
  ZoomIn = "fad:zoomin",
  More = "ri:more-line",
}
